# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ninja_metrics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ninja_metrics.proto',
  package='ninja_metrics',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13ninja_metrics.proto\x12\rninja_metrics\"p\n\x0cNinjaMetrics\x12\x17\n\x0fnum_input_files\x18\x01 \x01(\r\x12\x14\n\x0cnum_projects\x18\x02 \x01(\r\x12\x31\n\rproject_infos\x18\x03 \x03(\x0b\x32\x1a.ninja_metrics.ProjectInfo\"4\n\x0bProjectInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x0fnum_input_files\x18\x02 \x01(\rb\x06proto3'
)




_NINJAMETRICS = _descriptor.Descriptor(
  name='NinjaMetrics',
  full_name='ninja_metrics.NinjaMetrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_input_files', full_name='ninja_metrics.NinjaMetrics.num_input_files', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_projects', full_name='ninja_metrics.NinjaMetrics.num_projects', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='project_infos', full_name='ninja_metrics.NinjaMetrics.project_infos', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=150,
)


_PROJECTINFO = _descriptor.Descriptor(
  name='ProjectInfo',
  full_name='ninja_metrics.ProjectInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ninja_metrics.ProjectInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_input_files', full_name='ninja_metrics.ProjectInfo.num_input_files', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=204,
)

_NINJAMETRICS.fields_by_name['project_infos'].message_type = _PROJECTINFO
DESCRIPTOR.message_types_by_name['NinjaMetrics'] = _NINJAMETRICS
DESCRIPTOR.message_types_by_name['ProjectInfo'] = _PROJECTINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NinjaMetrics = _reflection.GeneratedProtocolMessageType('NinjaMetrics', (_message.Message,), {
  'DESCRIPTOR' : _NINJAMETRICS,
  '__module__' : 'ninja_metrics_pb2'
  # @@protoc_insertion_point(class_scope:ninja_metrics.NinjaMetrics)
  })
_sym_db.RegisterMessage(NinjaMetrics)

ProjectInfo = _reflection.GeneratedProtocolMessageType('ProjectInfo', (_message.Message,), {
  'DESCRIPTOR' : _PROJECTINFO,
  '__module__' : 'ninja_metrics_pb2'
  # @@protoc_insertion_point(class_scope:ninja_metrics.ProjectInfo)
  })
_sym_db.RegisterMessage(ProjectInfo)


# @@protoc_insertion_point(module_scope)
